    name: Update NSTC Typhoon Data Daily

    on:
      schedule:
        # 每天 UTC 時間 00:00 和 12:00 執行
        # 這對應於台灣時間上午 8:00 和 晚上 8:00 (UTC+8)
        # 您可以根據需要調整時間，例如 '0 0 * * *' 表示每天 UTC 00:00 (台灣時間上午 8 點)
        - cron: '0 0,12 * * *'
      workflow_dispatch: # 允許手動觸發此工作流程 (方便您測試)

    jobs:
      download_and_push_csv:
        runs-on: ubuntu-latest # 在一個最新的 Ubuntu Linux 虛擬機上運行這個任務
        steps:
          - name: Checkout repository # 第一步：將您的 GitHub 倉庫程式碼下載到這個虛擬機
            uses: actions/checkout@v3

          - name: Download CSV from NSTC # 第二步：下載 NSTC 的 CSV 檔案
            # 使用 curl 命令下載檔案
            # -k 或 --insecure 參數：這是關鍵！它會禁用 SSL 憑證驗證，讓 curl 可以連接到 mas.nstc.gov.tw
            # -o data/nstc_typhoon_index.csv：將下載的檔案儲存到 'data' 資料夾下，並命名為 'nstc_typhoon_index.csv'
            # 如果 'data' 資料夾不存在，curl 會自動創建它
            run: |
              mkdir -p data # 確保 data 目錄存在
              curl -k -o data/nstc_typhoon_index.csv "https://mas.nstc.gov.tw/OPENDATA/GetFile?format=csv&serialno=454&fileodr=1"
            
          - name: Commit and push changes # 第三步：將下載的 CSV 檔案提交回您的 GitHub 倉庫
            run: |
              # 設定 Git 使用者的名稱和電子郵件，這是 GitHub Actions 機器人的身份
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              # 將新下載或更新的 CSV 檔案添加到 Git 追蹤
              git add data/nstc_typhoon_index.csv
              # 檢查是否有實際的變動，如果沒有變動則不提交，避免不必要的提交歷史
              git diff --staged --quiet || git commit -m "Update NSTC typhoon data index CSV"
              # 將變動推送到 GitHub 倉庫
              git push
            env:
              # GITHUB_TOKEN 是一個由 GitHub Actions 自動提供的安全憑證
              # 它允許這個工作流程有權限提交到當前倉庫，您不需要自己設定
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
